require 'capistrano/rbenv'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/rails/console'
require 'capistrano/passenger'
# TODO
# https://github.com/the-cocktail?utf8=%E2%9C%93&q=capistrano&type=&language=
# https://github.com/komazarari/capistrano-locally
# https://github.com/yannlugrin/capistrano-git-push
